### ISSUE TITLE
ReferenceError: "local" is not defined. (js#9)

### ISSUE THREAD

**Issue by vldF** [JetBrains/intellij-ui-test-robot#157]
When the next code runs, I got the next error.
Code:
`find<TextEditorFixture>(EditorFixture.locator)
`
Error:
```
ReferenceError: "local" is not defined. (js#9)
com.intellij.remoterobot.client.IdeaSideException: ReferenceError: "local" is not defined. (js#9)
	at com.intellij.remoterobot.client.IdeRobotClient.throwIdeaSideError(IdeRobotClient.kt:142)
	at com.intellij.remoterobot.client.IdeRobotClient.processExecuteResponse(IdeRobotClient.kt:109)
	at com.intellij.remoterobot.client.IdeRobotClient.execute(IdeRobotClient.kt:63)
	at com.intellij.remoterobot.JavaScriptApi$DefaultImpls.runJs(JavaScriptApi.kt:57)
	at com.intellij.remoterobot.RemoteRobot.runJs(RemoteRobot.kt:32)
	at com.intellij.remoterobot.fixtures.Fixture.runJs(Fixture.kt:92)
	at com.intellij.remoterobot.fixtures.Fixture.runJs$default(Fixture.kt:85)
	at com.intellij.remoterobot.fixtures.EditorFixture.<init>(TextEditorFixture.kt:109)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at com.intellij.remoterobot.SearchContext$find$1.invoke(SearchContext.kt:69)
	at com.intellij.remoterobot.SearchContext$find$1.invoke(SearchContext.kt:51)
	at com.intellij.remoterobot.stepsProcessing.StepWorkerKt.step(StepWorker.kt:23)
	at com.intellij.remoterobot.SearchContext$DefaultImpls.find(SearchContext.kt:51)
	at com.intellij.remoterobot.fixtures.ContainerFixture.find(ContainerFixture.kt:12)
```

How can I avoid this error?

**Comment by nizienko** [comment]
Hello! I've just tried to run this code and it works fine for me. Are you sure that this is the right fragment of the code? Because the error appears in the constructor of `EditorFixture`, but your code creates a new `TextEditorFixture`.
Also, problems could come from the wrong locator you use when looking for `TextEditorFixture`. Could you please try this:
```
val textEditor = find<TextEditorFixture>(TextEditorFixture.locator)
println(textEditor.editor.text)
```

**Comment by vldF** [comment]
Sorry, I tried to fix my issue and I attached wrong code version
Could you, please, try next code?
`find<EditorFixture>(EditorFixture.locator)`

**Comment by nizienko** [comment]
this one also works for me. Could you please tell me what versions of remote-robot and fixtures do you use?

**Comment by nizienko** [comment]
is there any chance your robot-server plugin version is less than v0.11.5? if so, could you please update it?

**Comment by vldF** [comment]
I'm using version 0.11.9.166:
val remoteRobotVersion = "0.11.9.166"

dependencies {
    testImplementation("com.intellij.remoterobot:remote-robot:$remoteRobotVersion")
    testImplementation("com.intellij.remoterobot:remote-fixtures:$remoteRobotVersion")
}

Also, I can provide the last part of stacktrace:
```
Caused by: java.lang.Throwable
	at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:4236)
	at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:4214)
	at org.mozilla.javascript.ScriptRuntime.notFoundError(ScriptRuntime.java:4304)
	at org.mozilla.javascript.ScriptRuntime.name(ScriptRuntime.java:1924)
	at org.mozilla.javascript.gen.js_7._c_script_0(js:9)
	at org.mozilla.javascript.gen.js_7.call(js)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:412)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3545)
	at org.mozilla.javascript.gen.js_7.call(js)
	at org.mozilla.javascript.gen.js_7.exec(js)
	at com.intellij.remoterobot.services.js.RhinoJavaScriptExecutor.executeWithContext(RhinoJavaScriptExecutor.kt:37)
	at com.intellij.remoterobot.services.js.RhinoJavaScriptExecutor.execute(RhinoJavaScriptExecutor.kt:9)
	at com.intellij.remoterobot.services.IdeRobot$doAction$4.invoke(IdeRobot.kt:268)
	at com.intellij.remoterobot.services.IdeRobot$doAction$4.invoke(IdeRobot.kt:19)
	at com.intellij.remoterobot.services.IdeRobot.getResult(IdeRobot.kt:335)
	at com.intellij.remoterobot.services.IdeRobot.doAction(IdeRobot.kt:260)
	at com.intellij.remoterobot.RobotServerImpl$startServer$2$2$22$1.invoke(RobotServerImpl.kt:255)
	at com.intellij.remoterobot.RobotServerImpl$startServer$2$2$22$1.invoke(RobotServerImpl.kt:29)
	at com.intellij.remoterobot.RobotServerImpl$Companion.commonRequest(RobotServerImpl.kt:324)
	at com.intellij.remoterobot.RobotServerImpl$startServer$2$2$22.invokeSuspend(RobotServerImpl.kt:251)
	at com.intellij.remoterobot.RobotServerImpl$startServer$2$2$22.invoke(RobotServerImpl.kt)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:243)
	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:113)
	at io.ktor.util.pipeline.SuspendFunctionGun.execute(SuspendFunctionGun.kt:133)
	at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:77)
	at io.ktor.routing.Routing.executeResult(Routing.kt:148)
	at io.ktor.routing.Routing.interceptor(Routing.kt:35)
	at io.ktor.routing.Routing$Feature$install$1.invokeSuspend(Routing.kt:100)
	at io.ktor.routing.Routing$Feature$install$1.invoke(Routing.kt)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:243)
	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:113)
	at io.ktor.features.ContentNegotiation$Feature$install$1.invokeSuspend(ContentNegotiation.kt:113)
	at io.ktor.features.ContentNegotiation$Feature$install$1.invoke(ContentNegotiation.kt)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:243)
	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:113)
	at io.ktor.util.pipeline.SuspendFunctionGun.execute(SuspendFunctionGun.kt:133)
	at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:77)
	at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$2.invokeSuspend(DefaultEnginePipeline.kt:121)
	at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$2.invoke(DefaultEnginePipeline.kt)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:243)
	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:113)
	at io.ktor.util.pipeline.SuspendFunctionGun.execute(SuspendFunctionGun.kt:133)
	at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:77)
	at io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1.invokeSuspend(NettyApplicationCallHandler.kt:54)
	at io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1.invoke(NettyApplicationCallHandler.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:55)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.startCoroutineImpl(Builders.common.kt:182)
	at kotlinx.coroutines.BuildersKt.startCoroutineImpl(Unknown Source)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:145)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:54)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
	at io.ktor.server.netty.NettyApplicationCallHandler.handleRequest(NettyApplicationCallHandler.kt:37)
	at io.ktor.server.netty.NettyApplicationCallHandler.channelRead(NettyApplicationCallHandler.kt:29)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:61)
	at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:370)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	... 1 more
```

**Comment by nizienko** [comment]
Could you please check a version of the robot-server plugin:
 - launch `runIdeForUiTests` task;
 - Idea should be started;
 - check a plugin version in Installed plugins:
![image](https://user-images.githubusercontent.com/6516906/148960650-06eda41b-e336-42a8-bab9-925998c2dbf3.png)

Also your gradle.build.kts might be useful

**Comment by vldF** [comment]
Ohh, yeas, you're right, I have version 0.10.0. But I can't change it using gradle. I wrote the next code fragment:
```
tasks.downloadRobotServerPlugin {
    version = "0.11.11"
}
```

And I got the error:
```
Execution failed for task ':robot-tests:downloadRobotServerPlugin'.
> Could not resolve all files for configuration ':robot-tests:detachedConfiguration5'.
   > Could not resolve org.jetbrains.test:robot-server-plugin:0.11.11.
     Required by:
         project :robot-tests
      > Could not resolve org.jetbrains.test:robot-server-plugin:0.11.11.
         > Could not get resource *INTERNAL REPO URL*.
            > Could not GET *INTERNAL REPO URL* Received status code 401 from server: Unauthorized
      > Could not resolve org.jetbrains.test:robot-server-plugin:0.11.11.
         > Could not get resource 'https://jetbrains.bintray.com/intellij-third-party-dependencies/org/jetbrains/test/robot-server-plugin/0.11.11/robot-server-plugin-0.11.11.pom'.
            > Could not GET 'https://jetbrains.bintray.com/intellij-third-party-dependencies/org/jetbrains/test/robot-server-plugin/0.11.11/robot-server-plugin-0.11.11.pom'. Received status code 502 from server: Bad Gateway
```

But I wrote more repos:
```
repositories {
    mavenCentral()
    maven("https://packages.jetbrains.team/maven/p/ij/intellij-dependencies")
    maven("https://cache-redirector.jetbrains.com/intellij-third-party-dependencies/")
    maven("https://packages.jetbrains.team/maven/p/iuia/qa-automation-maven")
    maven(*INTERNAL REPO URL*)
}
```
So, what should I do to update robot server plugin?

**Comment by nizienko** [comment]
I assume that you also have an old version of [gradle-intellij-plugin](https://github.com/JetBrains/gradle-intellij-plugin) We had to move the library from bintray last year, and the old version doesn't support new location. I would suggest updating it to 1.3.0. Check [the migration guide](https://lp.jetbrains.com/gradle-intellij-plugin/)
