### ISSUE TITLE
Exception when starting IntelliJ 2022.1 for UI tests

### ISSUE THREAD

**Issue by zcervink** [JetBrains/intellij-ui-test-robot#182]
Unable to start IntelliJ 2022.1, exception appears (2021.3 and older starts without issue)

**Cmd run in src/test-project folder in shared library project (and also in projects to that are this library connected):**
`https://github.com/redhat-developer/intellij-common-ui-test-library/tree/main/src/test-project`

**Command:**
`./gradlew runIdeForUiTests -PideaVersion=IC-2022.1`

**Exception:**
```
!bootstrap.error.message.internal.error.please.refer.to.0!https://jb.gg/ide/critical-startup-errors!

java.lang.NoClassDefFoundError: com/intellij/openapi/util/SystemInfoRt
    at com.intellij.openapi.application.PathManager.getBinDirectories(PathManager.java:166)
    at com.intellij.openapi.application.PathManager.isIdeaHome(PathManager.java:154)
    at com.intellij.openapi.application.PathManager.getHomePathFor(PathManager.java:149)
    at com.intellij.openapi.application.PathManager.getHomePath(PathManager.java:94)
    at com.intellij.openapi.application.PathManager.loadProperties(PathManager.java:522)
    at com.intellij.idea.Main.bootstrap(Main.java:89)
    at com.intellij.idea.Main.main(Main.java:79)
Caused by: java.lang.ClassNotFoundException: com.intellij.openapi.util.SystemInfoRt
    at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
    at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
    ... 7 more

-----
!bootstrap.error.message.jre.details!11.0.14.1+1-b2043.25 x86_64 (JetBrains s.r.o.)
/Users/zcervink/.gradle/caches/modules-2/files-2.1/com.jetbrains/jbre/jbr_jcef-11_0_14_1-osx-x64-b2043.25/extracted/jbr/Contents/Home!
```

**Comment by zcervink** [comment]
**IMPORTANT UPDATE**: I have tried the above mentioned gradlew cmd in the root of this repo on localhost, no issue appears. There arre 2 possible reasonf for this issue:

1) there is an issue inside this project - not appearing when starting IDE from inside this project but appears after connecting this project to other project as dependency -> this project is unusable in other project
2) something in my project is badly configured - fix in my project can resolve this issue

**Comment by nizienko** [comment]
Hi, seems that was a [bug](https://youtrack.jetbrains.com/issue/IDEA-291192) I've checked your test project with 'org.jetbrains.intellij' version '1.5.3', seems it works fine with it.

**Comment by zcervink** [comment]
Hi @nizienko, thank you very much for your help, now everything is working as expected. Issue is resolved, I suggest to close this issue.
