### ISSUE TITLE
Wait for smart mode flaky with null project exception

### ISSUE THREAD

**Issue by ruomengz** [JetBrains/intellij-ui-test-robot#184]
Hi,

We follow the examples in this repo to wait for smart mode in our tests, this function times out sometimes in our integration tests.

https://github.com/JetBrains/intellij-ui-test-robot/blob/aa7c4bd84562bfedf4b50e1bb6c56e5057fb560d/ui-test-example/src/test/kotlin/org/intellij/examples/simple/plugin/pages/IdeaFrame.kt#L33-L45

When we checked the log, it shows that `project` is null in this call 

https://github.com/JetBrains/intellij-ui-test-robot/blob/aa7c4bd84562bfedf4b50e1bb6c56e5057fb560d/ui-test-example/src/test/kotlin/org/intellij/examples/simple/plugin/pages/IdeaFrame.kt#L48

```
2022-04-28 07:47:33,888 [  89163]   WARN - ctionSystem.impl.ActionUpdater - 566 ms to grab EDT for #update (com.intellij.codeInsight.actions.ReaderModeActionProvider$createAction$1) 
2022-04-28 07:47:33,889 [  89164]   WARN - ctionSystem.impl.ActionUpdater - 566 ms to grab EDT for CWMTelephonyGroup#update (com.jetbrains.rd.platform.codeWithMe.telephony.CWMTelephonyGroup) 
org.mozilla.javascript.WrappedException: Wrapped java.lang.IllegalArgumentException: Argument for @NotNull parameter 'project' of com/intellij/openapi/project/DumbService.isDumb must not be null (js#8)
	at org.mozilla.javascript.Context.throwAsScriptRuntimeEx(Context.java:1825)
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:227)
	at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:211)
	at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:35)
	at org.mozilla.javascript.gen.js_12._c_script_0(js:8)
	at org.mozilla.javascript.gen.js_12.call(js)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:380)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3868)
	at org.mozilla.javascript.gen.js_12.call(js)
	at org.mozilla.javascript.gen.js_12.exec(js)
	at com.intellij.remoterobot.services.js.RhinoJavaScriptExecutor.executeWithContext(RhinoJavaScriptExecutor.kt:44)
	at com.intellij.remoterobot.services.js.RhinoJavaScriptExecutor.execute(RhinoJavaScriptExecutor.kt:12)
	at com.intellij.remoterobot.services.IdeRobot$retrieveAny$4$1.executeInEDT(IdeRobot.kt:358)
	at com.intellij.remoterobot.services.IdeRobot$retrieveAny$4$1.executeInEDT(IdeRobot.kt:356)
	at org.assertj.swing.edt.GuiQuery.run(GuiQuery.java:42)
	at java.desktop/java.awt.event.InvocationEvent.dispatch([InvocationEvent.java:313](https://cs.corp.google.com/#search/&sq=package:%5Epiper$%20project:openjdk&q=java/awt/event/InvocationEvent.java:313))
	at java.desktop/java.awt.EventQueue.dispatchEventImpl([EventQueue.java:776](https://cs.corp.google.com/#search/&sq=package:%5Epiper$%20project:openjdk&q=java/awt/EventQueue.java:776))
	at java.desktop/java.awt.EventQueue$4.run([EventQueue.java:727](https://cs.corp.google.com/#search/&sq=package:%5Epiper$%20project:openjdk&q=java/awt/EventQueue.java:727))
	at java.desktop/java.awt.EventQueue$4.run([EventQueue.java:721](https://cs.corp.google.com/#search/&sq=package:%5Epiper$%20project:openjdk&q=java/awt/EventQueue.java:721))
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege([ProtectionDomain.java:85](https://cs.corp.google.com/#search/&sq=package:%5Epiper$%20project:openjdk&q=java/security/ProtectionDomain.java:85))
	at java.desktop/java.awt.EventQueue.dispatchEvent([EventQueue.java:746](https://cs.corp.google.com/#search/&sq=package:%5Epiper$%20project:openjdk&q=java/awt/EventQueue.java:746))
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:891)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:760)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:447)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:818)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:446)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:498)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters([EventDispatchThread.java:203](https://cs.corp.google.com/#search/&sq=package:%5Epiper$%20project:openjdk&q=java/awt/EventDispatchThread.java:203))
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter([EventDispatchThread.java:124](https://cs.corp.google.com/#search/&sq=package:%5Epiper$%20project:openjdk&q=java/awt/EventDispatchThread.java:124))
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy([EventDispatchThread.java:113](https://cs.corp.google.com/#search/&sq=package:%5Epiper$%20project:openjdk&q=java/awt/EventDispatchThread.java:113))
	at java.desktop/java.awt.EventDispatchThread.pumpEvents([EventDispatchThread.java:109](https://cs.corp.google.com/#search/&sq=package:%5Epiper$%20project:openjdk&q=java/awt/EventDispatchThread.java:109))
	at java.desktop/java.awt.EventDispatchThread.pumpEvents([EventDispatchThread.java:101](https://cs.corp.google.com/#search/&sq=package:%5Epiper$%20project:openjdk&q=java/awt/EventDispatchThread.java:101))
	at java.desktop/java.awt.EventDispatchThread.run([EventDispatchThread.java:90](https://cs.corp.google.com/#search/&sq=package:%5Epiper$%20project:openjdk&q=java/awt/EventDispatchThread.java:90))
Caused by: java.lang.IllegalArgumentException: Argument for @NotNull parameter 'project' of com/intellij/openapi/project/DumbService.isDumb must not be null
	at com.intellij.openapi.project.DumbService.$$$reportNull$$$0(DumbService.java)
	at com.intellij.openapi.project.DumbService.isDumb(DumbService.java)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke([Method.java:566](https://cs.corp.google.com/#search/&sq=package:%5Epiper$%20project:openjdk&q=java/lang/reflect/Method.java:566))
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:206)
	... 33 more
``` 

We also checked the video, the project opens and waits for 5 minutes until this test failed with timeout error.

Can someone please help us understand why `component.project` is null and how we can make this function more stable?

Thanks!

**Comment by shishovv** [comment]
Hi,
I've pushed possible fix for `IdeaFrame#isDumbMode`. Could you please try it and tell if it helps

**Comment by nizienko** [comment]
hello @ruomengz, can you please try another one fix?

**Comment by ruomengz** [comment]
Hey @nizienko 

Thank you for the fix! I am no longer seeing the exceptions.
