### ISSUE TITLE
Click seems to not working

### ISSUE THREAD

**Issue by Jonatha1983** [JetBrains/intellij-ui-test-robot#3]
Hi 

I tried to use this plugin on my mac - but it looks like the click is not working properly.

```Exceeded timeout (PT5S) for condition function (Failed to find 'Button' by 'text 'Finish'' in 5s) 
com.intellij.remoterobot.utils.WaitForConditionTimeoutException: Exceeded timeout (PT5S) for condition function (Failed to find 'Button' by 'text 'Finish'' in 5s) 
	at com.intellij.remoterobot.utils.RepeatUtilsKt.waitFor(RepeatUtils.kt:38)
	at com.intellij.remoterobot.utils.RepeatUtilsKt.waitFor$default(RepeatUtils.kt:33)
	at com.intellij.remoterobot.SearchContext$find$1.invoke(SearchContext.kt:51)
	at com.intellij.remoterobot.SearchContext$find$1.invoke(SearchContext.kt:15)
	at com.intellij.remoterobot.stepsProcessing.StepWorkerKt.step(StepWorker.kt:21)
	at com.intellij.remoterobot.SearchContext$DefaultImpls.find(SearchContext.kt:49)
	at com.intellij.remoterobot.fixtures.ContainerFixture.find(ContainerFixture.kt:11)
	at com.intellij.remoterobot.fixtures.CommonContainerFixture.button(CommonContainerFixture.kt:180)
```

I am using:
```
IntelliJ IDEA 2020.3 (Ultimate Edition)
Build #IU-203.5981.155, built on December 1, 2020
Licensed to Jonathan / Jonathan Gafner
Subscription is active until January 11, 2021
Runtime version: 11.0.9+11-b1145.21 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.16
GC: ParNew, ConcurrentMarkSweep
Memory: 6099M
Cores: 8
Registry: analyze.exceptions.on.the.fly=true
Non-Bundled Plugins: com.gafner.giv, com.dmarcotte.handlebars, org.jetbrains.kotlin, com.jetbrains.edu, com.google.gct.core, com.intellij.plugins.html.instantEditing, com.jetbrains.php
```

The find operation looks ending ok.
```
16:52:59 INFO : Search 'Welcome Frame' by 'type'
16:52:59 INFO : Search 'Action link' by 'New Project'
16:52:59 INFO : ..click
16:53:01 INFO : Search for dialog with title New Project
16:53:01 INFO :     Search 'Dialog' by 'title New Project'
16:53:22 WARN :         Failed on step: Search 'Dialog' by 'title New Project' (StepWorker.kt_step)
16:53:22 WARN :     Failed on step: Search for dialog with title New Project (StepWorker.kt_step)
16:53:22 INFO : Search 'Idea frame' by 'IdeFrameImpl type'
```

If I click on the "New Project" it failed on the next click:
```
16:54:03 INFO : Search 'Welcome Frame' by 'type'
16:54:03 INFO : Search 'Action link' by 'New Project'
16:54:03 INFO : ..click
16:54:05 INFO : Search for dialog with title New Project
16:54:05 INFO :     Search 'Dialog' by 'title New Project'
16:54:09 INFO :     ..click at 'Java'
16:54:11 INFO :     Search 'ComponentFixture' by '//div[@class='FrameworksTree']'
16:54:11 INFO :     ..click at 'Kotlin/JVM'
16:54:13 INFO :     Search 'Button' by 'text 'Next''
16:54:13 INFO :     ..click
16:54:14 INFO :     Search 'Button' by 'text 'Finish''
16:54:20 WARN :         Failed on step: Search 'Button' by 'text 'Finish'' (StepWorker.kt_step)
16:54:20 WARN :     Failed on step: Search for dialog with title New Project (StepWorker.kt_step)
16:54:20 INFO : Search 'Idea frame' by 'IdeFrameImpl type'
```
The robot thinks the click went ok but it did not.

**Comment by nizienko** [comment]
Could you please check `Security & Privacy` -> `Accessibility` -> `Allow the apps below to control your computer` and select the IntelliJ Idea.

**Comment by Jonatha1983** [comment]
@nizienko  WORKED!!!!! THANKS!!!!

**Comment by Jonatha1983** [comment]
Is it ok If I 'll add it to a README.md under the UI-test-example and open a PR?  I'll create a troubleshooting section if that is ok with you. 

I also did a change in the RemoteRobot - in case one wants to see the HTTP call and response they can pass a system property and it will create an OkHttpClient with an interceptor to log the calls.

**Comment by nizienko** [comment]
@Jonatha1983 of course please feel free to PR! Thanks for that!

**Comment by Jonatha1983** [comment]
@nizienko  - I am having some issues defining the debug retrofit with a system property.

I added to the RemoteRobot the following:
```
    val okHttpClient: OkHttpClient = if (System.getProperty("debug-retrofit")?.equals("enable") ?: false) {
        val interceptor: HttpLoggingInterceptor = HttpLoggingInterceptor().apply {
            this.level = HttpLoggingInterceptor.Level.BODY
        }
        OkHttpClient.Builder().apply {
            this.addInterceptor(interceptor)
        }.build()
    } else {
        DefaultHttpClient.client
    }
   ```
    
and in the runIdeForUiTests in the example project:
```
systemProperty "debug-retrofit", "enable"
```
But it the RemoteRobot does not get that. If I am enforcing with 
```
if (true)
```
It does work. 

My guess is that there are 2 processes and the RemoteRobot class is not invoked as part of the 
``` runIdeForUiTests ``` but on the other process. 

Any suggestions about it?
I'll open a PR and let me know what you think,  I can leave it as a comment or remove it completely if we don't find a solution. 

Thanks
