### ISSUE TITLE
"Unable to create converter for class com.intellij.remoterobot.client.RetrieveResponse" on JDK17

### ISSUE THREAD

**Issue by JohnLBergqvist** [JetBrains/intellij-ui-test-robot#355]
Hi, when starting the robot server (which i've confirmed is activate the correct URL), and calling `remoteRobot.getOs();`, I get the following exception (when built using JDK17):
```
java.lang.IllegalArgumentException: Unable to create converter for class com.intellij.remoterobot.client.RetrieveResponse
    for method IdeRobotApi.retrieve
	at retrofit2.Utils.methodError(Utils.java:54)
	at retrofit2.HttpServiceMethod.createResponseConverter(HttpServiceMethod.java:126)
	at retrofit2.HttpServiceMethod.parseAnnotations(HttpServiceMethod.java:85)
	at retrofit2.ServiceMethod.parseAnnotations(ServiceMethod.java:39)
	at retrofit2.Retrofit.loadServiceMethod(Retrofit.java:202)
	at retrofit2.Retrofit$1.invoke(Retrofit.java:160)
	at jdk.proxy2/jdk.proxy2.$Proxy12.retrieve(Unknown Source)
	at com.intellij.remoterobot.client.IdeRobotClient.retrieve(IdeRobotClient.kt:75)
	at com.intellij.remoterobot.JavaScriptApi$DefaultImpls.callJs(JavaScriptApi.kt:78)
	at com.intellij.remoterobot.RemoteRobot.callJs(RemoteRobot.kt:32)
	at com.intellij.remoterobot.JavaScriptApi$DefaultImpls.callJs(JavaScriptApi.kt:67)
	at com.intellij.remoterobot.RemoteRobot.callJs(RemoteRobot.kt:32)
	at com.intellij.remoterobot.RemoteRobot.getOs(RemoteRobot.kt:68)
```
When using JDK11, this does not occur. 

I'm using v`0.11.20` of `com.intellij.remoterobot.remote-robot`

**Comment by shishovv** [comment]
Hi, try to pass jvm arg `--add-opens java.base/java.lang=ALL-UNNAMED` to the test task

**Comment by JohnLBergqvist** [comment]
> --add-opens java.base/java.lang=ALL-UNNAMED

I've tried this but unfortunately it's had no effect.

**Comment by JohnLBergqvist** [comment]
> Hi, try to pass jvm arg `--add-opens java.base/java.lang=ALL-UNNAMED` to the test task

I've just tried this, but unfortunately it's had no effect.

**Comment by g-kozinets** [comment]
Had the same issue on jdk17 when I tried to launch tests on Intellij runner instead of Gradle. Adding `--add-opens java.base/java.lang=ALL-UNNAMED` to the Run Configuration solved this issue for me
