### ISSUE TITLE
Running IU-2021.2 in GitHub Actions on ubuntu doesn´t work 

### ISSUE THREAD

**Issue by richard0202** [JetBrains/intellij-ui-test-robot#356]
I am trying to run IntelliJ IDEA Ultimate 2021.2 (IU-2021.2) in GitHub Actions, but it is producing errors.

Commands I am running in job workflow:
```bash
export DISPLAY=:99.0
Xvfb -ac :99 -screen 0 1920x1080x16 &
./gradlew runIdeForUiTests -PideaVersion=IU-2021.2 -Drobot-server.port=8580
```

Stderr in GitHub Actions on ubuntu-latest:
```java
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Aug 31, 2023 1:45:28 PM java.util.prefs.FileSystemPreferences$6 run
WARNING: Prefs file removed in background /home/runner/.java/.userPrefs/prefs.xml
2023-08-31 13:45:29,212 [    588]   WARN - llij.ide.plugins.PluginManager - id redefinition ([row,col,system-id]: [2,3,"product classpath"]) 

(java:2401): dbind-WARNING **: 13:45:31.372: AT-SPI: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files
2023-08-31 13:45:33,440 [   4816]  ERROR - llij.ide.plugins.PluginManager - null 
java.lang.NullPointerException
	at java.desktop/sun.awt.SunToolkit.postEvent(SunToolkit.java)
	at java.desktop/sun.awt.X11.XWindow.postEvent(XWindow.java:435)
	at java.desktop/sun.awt.X11.XComponentPeer.endLayout(XComponentPeer.java:758)
	at java.desktop/java.awt.Container.validateTree(Container.java:1737)
	at java.desktop/java.awt.Container.validate(Container.java:1657)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2782)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:408)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
2023-08-31 13:45:33,476 [   4852]  ERROR - llij.ide.plugins.PluginManager - IntelliJ IDEA 2021.2  Build #IU-212.4746.92 
2023-08-31 13:45:33,502 [   4878]  ERROR - llij.ide.plugins.PluginManager - JDK: 11.0.11; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o. 
2023-08-31 13:45:33,506 [   4882]  ERROR - llij.ide.plugins.PluginManager - OS: Linux 

Start Failed
Internal error. Please refer to https://jb.gg/ide/critical-startup-errors

java.lang.NullPointerException
	at java.desktop/sun.awt.SunToolkit.postEvent(SunToolkit.java)
	at java.desktop/sun.awt.X11.XWindow.postEvent(XWindow.java:435)
	at java.desktop/sun.awt.X11.XComponentPeer.endLayout(XComponentPeer.java:758)
	at java.desktop/java.awt.Container.validateTree(Container.java:1737)
	at java.desktop/java.awt.Container.validate(Container.java:1657)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2782)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:408)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

-----
Your JRE: 11.0.11+9-b1504.13 amd64 (JetBrains s.r.o.)
/home/runner/.gradle/caches/modules-2/files-2.1/com.jetbrains/jbre/jbr_jcef-11_0_11-linux-x64-b1504.13/extracted/jbr
Aug 31, 2023 1:45:34 PM java.util.prefs.FileSystemPreferences$6 run
WARNING: Prefs file removed in background /home/runner/.java/.userPrefs/jetbrains/prefs.xml

Also, a UI exception occurred on an attempt to show the above message
java.lang.NullPointerException
	at java.desktop/sun.awt.SunToolkit.postEvent(SunToolkit.java)
	at java.desktop/sun.awt.X11.XWindow.postEvent(XWindow.java:435)
	at java.desktop/sun.awt.X11.XContentWindow.handleResize(XContentWindow.java:158)
	at java.desktop/sun.awt.X11.XContentWindow.setContentBounds(XContentWindow.java:130)
	at java.desktop/sun.awt.X11.XDecoratedPeer.reconfigureContentWindow(XDecoratedPeer.java:742)
	at java.desktop/sun.awt.X11.XDecoratedPeer.reshape(XDecoratedPeer.java:635)
	at java.desktop/sun.awt.X11.XDecoratedPeer.reshape(XDecoratedPeer.java:716)
	at java.desktop/sun.awt.X11.XDecoratedPeer.setBounds(XDecoratedPeer.java:729)
	at java.desktop/java.awt.Component.reshapeNativePeer(Component.java:2436)
	at java.desktop/java.awt.Component.reshape(Component.java:2384)
	at java.desktop/java.awt.Window.reshape(Window.java:970)
	at java.desktop/java.awt.Component.setBounds(Component.java:2342)
	at java.desktop/java.awt.Window.setBounds(Window.java:3548)
	at java.desktop/java.awt.Window.setClientSize(Window.java:976)
	at java.desktop/java.awt.Window.pack(Window.java:829)
	at java.desktop/javax.swing.JOptionPane.initDialog(JOptionPane.java:991)
	at java.desktop/javax.swing.JOptionPane.createDialog(JOptionPane.java:972)
	at java.desktop/javax.swing.JOptionPane.showOptionDialog(JOptionPane.java:871)
	at java.desktop/javax.swing.JOptionPane.showMessageDialog(JOptionPane.java:670)
	at java.desktop/javax.swing.JOptionPane.showMessageDialog(JOptionPane.java:641)
	at com.intellij.idea.Main.showMessage(Main.java:281)
	at com.intellij.idea.Main.showMessage(Main.java:219)
	at com.intellij.ide.plugins.StartupAbortedException.logAndExit(StartupAbortedException.java:88)
	at com.intellij.ide.plugins.StartupAbortedException.processException(StartupAbortedException.java:36)
	at com.intellij.ide.IdeEventQueue.processException(IdeEventQueue.java:622)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:411)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':runIdeForUiTests'.
> Process 'command '/home/runner/.gradle/caches/modules-2/files-2.1/com.jetbrains/jbre/jbr_jcef-11_0_11-linux-x64-b1504.13/extracted/jbr/bin/java'' finished with non-zero exit value 3

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org/

BUILD FAILED in 2m 3s
```

Stdout in GitHub Actions on ubuntu-latest:
```java
Starting a Gradle Daemon, 1 busy Daemon could not be reused, use --status for details

> Task :initializeIntelliJPlugin
[gradle-intellij-plugin :initializeIntelliJPlugin] Gradle IntelliJ Plugin is outdated: 1.14.1. Update `org.jetbrains.intellij` to: 1.15.0

> Task :downloadRobotServerPlugin
> Task :patchPluginXml UP-TO-DATE
> Task :verifyPluginConfiguration
> Task :compileJava

> Task :processResources UP-TO-DATE
> Task :classes
> Task :setupInstrumentCode
> Task :instrumentCode
> Task :instrumentedJar
> Task :jar
> Task :prepareUiTestingSandbox

> Task :runIdeForUiTests

> Task :runIdeForUiTests FAILED
> Task :classpathIndexCleanup SKIPPED
12 actionable tasks: 10 executed, 2 up-to-date
```

**Comment by richard0202** [comment]
Hi, thank you for your quick reply. I have added sleep for 60 seconds.

Stdout:
```java
Starting a Gradle Daemon, 1 busy Daemon could not be reused, use --status for details

> Task :initializeIntelliJPlugin
[gradle-intellij-plugin :initializeIntelliJPlugin] Gradle IntelliJ Plugin is outdated: 1.14.1. Update `org.jetbrains.intellij` to: 1.15.0

> Task :downloadRobotServerPlugin
> Task :patchPluginXml UP-TO-DATE
> Task :verifyPluginConfiguration
> Task :compileJava

> Task :processResources UP-TO-DATE
> Task :classes
> Task :setupInstrumentCode
> Task :instrumentCode
> Task :instrumentedJar
> Task :jar
> Task :prepareUiTestingSandbox

> Task :runIdeForUiTests
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fb65e97fb38, pid=2397, tid=2416
#
# JRE version: OpenJDK Runtime Environment JBR-11.0.11.9-1504.13-jcef (11.0.11+9) (build 11.0.11+9-b1504.13)
# Java VM: OpenJDK 64-Bit Server VM JBR-11.0.11.9-1504.13-jcef (11.0.11+9-b1504.13, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# V  [libjvm.so+0x57fb38]  metaspace::ChunkManager::split_chunk(unsigned long, metaspace::Metachunk*)+0x58
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport -p%p -s%s -c%c -d%d -P%P -u%u -g%g -- %E" (or dumping to /home/runner/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIU/2021.2/31f9496f635cec87427837101e04cbcddfb544d7/ideaIU-2021.2/bin/core.2397)
#
# An error report file with more information is saved as:
# /home/runner/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIU/2021.2/31f9496f635cec87427837101e04cbcddfb544d7/ideaIU-2021.2/bin/hs_err_pid2397.log
#
# If you would like to submit a bug report, please visit:
#   https://bugreport.java.com/bugreport/crash.jsp
#

> Task :runIdeForUiTests FAILED
> Task :classpathIndexCleanup SKIPPED
12 actionable tasks: 10 executed, 2 up-to-date
```

Stderr:
```java
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Sep 01, 2023 8:50:21 AM java.util.prefs.FileSystemPreferences$6 run
WARNING: Prefs file removed in background /home/runner/.java/.userPrefs/prefs.xml
2023-09-01 08:50:21,618 [    764]   WARN - llij.ide.plugins.PluginManager - id redefinition ([row,col,system-id]: [2,3,"product classpath"]) 

(java:2397): dbind-WARNING **: 08:50:23.098: AT-SPI: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':runIdeForUiTests'.
> Process 'command '/home/runner/.gradle/caches/modules-2/files-2.1/com.jetbrains/jbre/jbr_jcef-11_0_11-linux-x64-b1504.13/extracted/jbr/bin/java'' finished with non-zero exit value 134

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org/

BUILD FAILED in 3m 6s
```

**Comment by nizienko** [comment]
wow! it's crashed! And I've seen it two years ago https://youtrack.jetbrains.com/issue/JBR-3632
Can you try the same with other Idea versions? Is 2022.2/2023.2 also crashes on the same setup?

**Comment by richard0202** [comment]
Yeah it seems that 2023.2 works fine 👍 So it looks like it is a problem only with older versions.

**Comment by nizienko** [comment]
I guess there is nothing we can do on the remote-robot side in this issue. If you need assist with the old version please use [JBR issue](https://youtrack.jetbrains.com/issue/JBR-3632)
