### ISSUE TITLE
Launcher. Two vmoption file on linux

### ISSUE THREAD

**Issue by nizienko** [JetBrains/intellij-ui-test-robot#387]
`java.io.FileNotFoundException: failed to find default vmoptions file
	at com.intellij.remoterobot.launcher.IdeLauncher.readIdeDefaultVmOptions(IdeLauncher.kt:83)
	at com.intellij.remoterobot.launcher.IdeLauncher.launchIde(IdeLauncher.kt:33)
	at com.metalbear.mirrord.MirrordPluginTest$Companion.startIdea(MirrordPluginTest.kt:54)`

**Comment by TarCV** [comment]
I got similar issue with Mac and Win too. For me it is caused by `*_client64.vmoptions` files which present since around 2023.3 versions.
