### ISSUE TITLE
Cannot use JTableFixture: JS error "JTableTextCellReader is not a function, it is object"

### ISSUE THREAD

**Issue by g-kozinets** [JetBrains/intellij-ui-test-robot#421]
Framework version: 0.11.22
Intellij Idea version: 2021.3.2

I want to access cells of some JTable elements and I decided that I sould use JTableFixture for this.
But when I try to create JTableFixture object I get this error: 
```
TypeError: [JavaPackage com.intellij.remoterobot.fixtures.dataExtractor.server.textCellRenderers.JTableTextCellReader] is not a function, it is object. (js#10)

com.intellij.remoterobot.client.IdeaSideException: TypeError: [JavaPackage com.intellij.remoterobot.fixtures.dataExtractor.server.textCellRenderers.JTableTextCellReader] is not a function, it is object. (js#10)
	at app//com.intellij.remoterobot.client.IdeRobotClient.throwIdeaSideError(IdeRobotClient.kt:141)
	at app//com.intellij.remoterobot.client.IdeRobotClient.processExecuteResponse(IdeRobotClient.kt:108)
	at app//com.intellij.remoterobot.client.IdeRobotClient.execute(IdeRobotClient.kt:63)
	at app//com.intellij.remoterobot.JavaScriptApi$DefaultImpls.runJs(JavaScriptApi.kt:57)
	at app//com.intellij.remoterobot.RemoteRobot.runJs(RemoteRobot.kt:32)
	at app//com.intellij.remoterobot.fixtures.Fixture.runJs(Fixture.kt:92)
	at app//com.intellij.remoterobot.fixtures.Fixture.runJs$default(Fixture.kt:85)
	at app//com.intellij.remoterobot.fixtures.JTableFixture.<init>(JTableFixture.kt:17)
```
Steps to reproduce:

- Open intellij-ui-test-robot project
- Create simple test in any existing (or new) test class in ui-test-example module:

```
@Test
 void getJTableTest(final RemoteRobot remoteRobot) {
     JTableFixture tableFixture = remoteRobot.find(JTableFixture.class, Locators.byXpath("//div[@class='JTable']"));
}
```

- Launch ide via runIdeForUiTests task
- In the launched ide: Open any window with table, for example: Customize > All Settings > Tools > Web Browsers and Preview
- Launch getJTableTest() test

**Comment by g-kozinets** [comment]
Finally found out what was the problem. Turns out that my remote-robot dependencies were 0.11.22 version but remote-robot plugin had 0.11.6 version in dowloadRemoteServerPlugin gradle task

I had to use older version of Remote Server plugin, because in my environment I couldn't download the last version via gradle task that is why I used different versions

**Comment by g-kozinets** [comment]
Finally found out what was the problem. Turns out that my remote-robot dependencies were 0.11.22 version but remote-robot plugin had 0.11.6 version in dowloadRemoteServerPlugin gradle task

I had to use older version of Remote Server plugin, because in my environment I couldn't download the last version via gradle task that is why I used different versions
